### PR TITLE
bump version for peerDependency react to ^17.0.0

### PR DESCRIPTION
**Pull request by rene-mueller**
we need peer dependency support for react 17

### CODE REVIEW

**Comment by Denpex** [comment]
@kciter can you please merge this to master

**Comment by brian-dlee** [comment]
@rene-mueller I think the package.json version will need to be bumped to `1.4.1`.

**Comment by rene-mueller** [comment]
@brian-dlee thx I will do this tomorrow :)

**Comment by jackdpeterson** [comment]
@kciter  -- I'm proposing https://github.com/kciter/react-barcode/pull/55 as a replacement to this PR.

**Comment by rene-mueller** [comment]
Closed pr cause #55 is already merged

**Pull request closed without merging**
