### PR TITLE
Fix error: "Module not found: create-react-class"

### PR DESCRIPTION
**Pull request by oonsamyi**
#21

### CODE REVIEW

**Comment by renanbandeira** [comment]
Could you run your app with these changes? I have a can't resolve react-barcode even with the library from your repository installed.

**Comment by oonsamyi** [comment]
Yes I can. Have you installed the library from the [patch-1](https://github.com/oonsamyi/react-barcode/tree/patch-1) branch?

**Comment by marr** [comment]
Any chance of this getting merged soon?

**Comment by nolan-m** [comment]
@kciter Could you merge this in and create a new release?

**Comment by kciter** [comment]
I'm sorry!!  😢

**Pull request merged**
