### PR TITLE
add support for img element

### PR DESCRIPTION
**Pull request by benhancockco**
I've added a small snippet of code to enable the barcode to rendered as an `` element (alongside the existing `<svg>` and `<canvas>` elements). Full jsbarcode documentation [here](https://www.npmjs.com/package/jsbarcode).

### CODE REVIEW

**Comment by kachkaev** [comment]
@benhancockco do you think this can partially enable server-side rendering (https://github.com/kciter/react-barcode/issues/19)?

**Comment by benhancockco** [comment]
@kachkaev unfortunately this will not enable server-side rendering to any degree.

**Comment by kachkaev** [comment]
What changes would be required to make SSR happen? @benhancockco and @kciter, could you please share your thoughts in https://github.com/kciter/react-barcode/issues/19? If SSR is possible by the upstream lib, but there's just not enough time to enable it, I'll be happy to work on a PR.

**Comment by benhancockco** [comment]
Unfortunately my knowledge on SSR is limited so I am unable to assist on this front., @kachkaev.

**Pull request merged**
