### PR TITLE
Fix bug check wrong version React 16.12.0

### PR DESCRIPTION
**Pull request by lphuctai**
This condition cause crash my app.
react-barcode.js:18 Uncaught TypeError: ref.getDOMNode is not a function

### CODE REVIEW

**Comment by colepanike** [comment]
NOTE: Fixes #38

**Comment by kachkaev** [comment]
@kciter 🙏

**Comment by quaj** [comment]
+1 @kciter

**Comment by quaj** [comment]
May I fork to a new package?

**Comment by kciter** [comment]
Sorry I'm late.

**Comment by colepanike** [comment]
@kciter Please bump the version and publish to npm

**Comment by tiendn** [comment]
@kciter please 🙏

**Comment by colepanike** [comment]
Incase anyone is stuck right now, set your react version explicitly to 16.11.0 with `npm install react@16.11.0 --save`

Make sure both your package.json and your package-lock.json have this version with NO ^ before it. Then your builds should work for now.

**Pull request merged**
